query ($betCreatedTopic: [Bytes32!]!) {
  block {
    hash
    logs(filter: { addresses: [], topics: [$betCreatedTopic] }) {
      data
      topics
      transaction {
        hash
        from {
          address
        }
        value
        status
      }
    }
  }
}
