query {
  block {
    hash
    logs(
      filter: {
        addresses: ["0xf6927810102d37be74f585168064feece9a672c7"]
        topics: [
          ["0x9a0204d7d0a90e95e52d820bb9bd7713c5dc79105b86cfe6073c827a88b999bb"]
        ]
      }
    ) {
      data
      topics
      transaction {
        hash
        from {
          address
        }
        value
        status
      }
    }
  }
}
