query {
  block {
    hash
    logs(
      filter: {
        addresses: ["0xe1b046Ae7b3ea1d5041274c707bc6298884E3A71"]
        topics: [
          ["0x807e743b9b5ddc6f51022646b7a8cae5649afbf10bd3d28a5c11a74a9916e651"]
        ]
      }
    ) {
      data
      topics
      transaction {
        hash
        from {
          address
        }
        value
        status
      }
    }
  }
}
