query {
  block {
    hash
    timestamp
    logs(
      filter: {
        addresses: ["0xf6927810102d37be74f585168064feece9a672c7"]
        topics: [
          ["0x5c0a21548aa1b914099d44da75211e1a191895cf247f91eb306de0c7a7864d24"]
        ]
      }
    ) {
      data
      topics
      transaction {
        hash
        from {
          address
        }
        value
        status
      }
    }
  }
}
