name: Deploy backend (dev environment)

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    environment: "DEV"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK stack
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_BOT_APP_KEY: ${{ secrets.TWITTER_BOT_APP_KEY }}
          TWITTER_BOT_APP_SECRET: ${{ secrets.TWITTER_BOT_APP_SECRET }}
          TWITTER_BOT_ACCESS_TOKEN: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN }}
          TWITTER_BOT_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_BOT_ACCESS_TOKEN_SECRET }}
          TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          DEPLOYMENT_ENV: "development" # this should match the lib/utils.ts enum DeploymentEnv
        run: make deploy
