name: Tests and Type Checking

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Check for build errors
        run: npx tsc --noEmit
